### ISSUE TITLE
Any plan to make it a mobile app?

### ISSUE THREAD

**Issue by uilnauyis** [sotch-pr35mac/syng#105]
Hmm not sure if it is suitable to raise this as a request here. Anyway, I suggest it would be nice to have syng running on mobile phones.  Do you have any plan for developing mobile version of syng?

**Comment by sotch-pr35mac** [comment]
Yes, a mobile app is on the roadmap. First I want to finish up some of the features of the desktop version (like document reader), then build a web version, and then work on building a mobile app for both Android and iOS. Since a lot of the feature for the mobile app (like optical character recognition and bookmarks sync between devices) require a server I’ll build the web interface first, and then go to mobile.

**Comment by uilnauyis** [comment]
Happy to know that!
