### ISSUE TITLE
Native Haiku app

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#124]
Build a native [Haiku](https://www.haiku-os.org/) app. I believe - over time - Haiku will massively gain in importance. I've downloaded the beta and I'm so impressed that I'm considering to leave the Linux world for it. 

I have to get some information on what programming languages and frameworks are most commonly used for application development in Haiku and whether there are any more universal cross-platform solutions to get it to run on GNU/Linux, Haiku, macOS and Windows.

**Comment by sotch-pr35mac** [comment]
I’m definitely open to developing Syng natively for more systems (I want to migrate from electron for a true native experience). My main concern is maintain that many different codebases, if you come across a language or framework that can be used for both GNU/Linux and Haiku that would be ideal, otherwise I can’t gaurentee that Haiku will be as current as the other versions. Please let me know if you find anything!

**Comment by sotch-pr35mac** [comment]
Clearing out tasks that are no longer relevant.
