### ISSUE TITLE
Harfbuzz version too old

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [sotch-pr35mac/syng#151]
When trying to run syng on a Manjaro machine (I don't have access to my main Arch Linux system, but I'd expect similar behaviour), the app won't start but output following error:
`(Syng:147159): Pango-ERROR **: 06:57:35.961: Harfbuzz version too old (1.0.5)`

On my system the version number of Harfbuzz is : 2.8.0-1

**Comment by sotch-pr35mac** [comment]
Sorry for the late reply, I recently moved and things have been a bit chaotic. 

Thank you for letting me know. It looks like this issue is with the electron framework that Syng is built on top of. It has been updated in the V2 of Syng I have been working on but I doubt that would be ready in time for you to consume it in a reasonable time frame. 

I will try and update the electron version sometime this week and see if I can't get this resolved for you. Would you be comfortable building Syng from source from a bug fix branch when I put the fix together to validate that the fix is working for you, as I don't have a Linux system to test against setup at the moment.

**Comment by antoinejoly76** [comment]
Hi, facing same error, I can try build from source if you give me basic instructions.
Actually I was thinking, would you be interested in someone trying to build a flatpak as it would make the distribution of your software much easier on Linux?

**Comment by sotch-pr35mac** [comment]
Hi @antoinejoly76, thank you for offering to build from source. I've attached some instructions below, but if you run into any issues please don't hesitate to reach back out. 

There are a couple of requirements to getting started:
- [Install Node.js](https://nodejs.org/en/download/) on your system if you don't have it installed already
- [Install NPM](https://nodejs.org/en/download/) on your system if you don't have it installed already

Steps to validating that the fix is working properly
1. Clone the repo
2. Checkout the bug fix branch. `git checkout pw/fix-harfbuzz-version`
3. Install dependencies. `npm install`
4. Build `npm run build`
5. Start Syng `npm start`

If you are able to start Syng and make a query then the fix should be working.

**Comment by antoinejoly76** [comment]
Hi @sotch-pr35mac, sorry for the delay. I was able to build from source and it works fine with the fix.

**Comment by sotch-pr35mac** [comment]
@antoinejoly76 No worries, thanks for checking that out. I'll get started on cutting an updated release with the fix included.

**Comment by ChristophSchmidpeter** [comment]
Thanks for fixing :)
