### ISSUE TITLE
Linux Dependencies

### ISSUE THREAD

**Issue by XingShelly** [sotch-pr35mac/syng#174]
Please update the dependencies of the Linux version, as it no longer works anymore.
I understand that you are busy and this is just a side project for you. however. This is literally the best Ch-En dictionary out there! Please maintain it more often.

Thank you so much. I really wish you would just update it to work.

**Comment by rmikedown** [comment]
I've got the same problem. Would love to get this up and running. #teamlinux

**Comment by sotch-pr35mac** [comment]
Apologies for not getting to this item sooner, I just had a baby and my few available free cycles have been going into the v2 rewrite. Thank you for reporting this issue. The fix is now on master. I currently don't have access to a Linux machine that I can verify everything is working as expected on. Before I package the app for release, if you could verify everything is working as expected after the update by following the steps below, that would be incredibly helpful. 

#### Verifying the update
1. Clone the repo
2. Pull latest master
3. `npm install`
4. `npm run build`
5. `npm start`
6. Validate the app starts as expected. 

#### Packaging Preferences
Are there any preferences for the packaging of the Linux app? I don't have the cycles to do app packaging on multiple distros, so a distro-agnostic solution would be my preference. I see @XingShelly you've opened up another Issue #175 requesting either an AppImage or Flatpak, but I wanted to surface the question here since there are more participants to this thread that may also have a preference.

**Comment by rmikedown** [comment]
Congrats on the baby! I can try to verify the update a bit later. As for packaging, my preference would be a Flatpak.

**Comment by sotch-pr35mac** [comment]
@rmikedown Thanks giving that a shot. The output of the audit is just letting us know which packages are out of date and have known vulnerabilities. These don't need to be fixed to validate the update. It would be helpful to understand what the error was that you got running `npm install`? If you wouldn't mind also including the output of `npm -v && node -v`, that'll help me identify what the issue is you are facing installing the dependencies.

**Comment by rmikedown** [comment]
> 

Actually I hadn't run all the commands. I was getting all these warnings and thought something was wrong. But the app runs.

By the way, this is the first time using it for me, and I really like the clipboard reader. It's just like pleco. Do I need to configure it to say the words I click on? And is there a way to get it to read all the words on the page?

**Comment by sotch-pr35mac** [comment]
Thanks for verifying the fix is working. I'll cut an updated release with the fix sometime this week. 

For the reader feature, when you click on a word from the text you've pasted in, the entry for that word will pop up at the bottom. Or you're looking for having the word read aloud, there should be a speaker icon in the entry at the bottom next to the word's characters.

**Comment by sotch-pr35mac** [comment]
Closing since the fix has been validated.
