### ISSUE TITLE
Solus installation candidate

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#54]
Is it possible to add a Solus installation candidate or to include it on a list of supported platforms? Looking forward to your next release. I have filed a request to have Syng included into the Solus repositories here: https://dev.solus-project.com/T957
Solus: https://solus-project.com/

**Comment by sotch-pr35mac** [comment]
Thank you for using Syng! I appreciate your support of the project. 
I am packaging the new release now and it should be up in the next day or so.
I'd be more than willing to try and create a Solus installation candidate, but you will have to forgive my ignorance in regards to the process, I am not too familiar with Solus OS. I am sorry to hear that your request for Syng to be added to the Solus repositories was denied due to my development schedule and Syng's beta status. The unfortunate truth is that with my class and work schedule it can be difficult to find adequate time to push new features and get Syng out of beta. But I can assure you that development will continue. 

Just to make sure we are on the same page: What do you mean by adding Solus to a list of supported platforms? If I'm not mistaken the Linux installation candidate should work on Solus, using the `install.sh', or 'update.sh'. 

For packaging Syng for Solus: Are you familiar with the process for packaging an app for Solus?

**Comment by sotch-pr35mac** [comment]
Is your question similar to this issue: #41

**Comment by baimafeima** [comment]
> For packaging Syng for Solus: Are you familiar with the process for packaging an app for Solus?

Solus now has a packaging guide available on its website: https://solus-project.com/articles/packaging/

Once your software is out of beta, I will suggest it for reevaluation on the Solus dev tracker, so there is no need to deal with Solus packaging as your software is not accepted for inclusion (yet).

**Comment by baimafeima** [comment]
I am looking forward to your work on Syng and once it is out of beta, I will make sure that it is reconsidered for inclusion on the above-mentioned development tracker. Closing this issue as it is not connected to a specific feature request.
