### ISSUE TITLE
Flatpak or Snap support

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#77]
Could you add a Flatpak release? http://flatpak.org/
This would blend in nicely with your idea of cross-platform support and you would only have to maintain one release instead of many such as .deb or .rpm and whatnot. As I don't use a Debian-based operating system, I don't have any use for .deb files. 
Solus: https://solus-project.com/2017/01/18/adopting-flatpak-to-reassemble-third-party-applications/
Fedora: https://fedoramagazine.org/introducing-flatpak/

**Comment by sotch-pr35mac** [comment]
This is an excellent idea and is definitely already being considered for the next release. 

Thank you for your interest in Syng!

**Comment by sotch-pr35mac** [comment]
just built flatpak package for v1.0.0 release.

**Comment by baimafeima** [comment]
That sounds great! Will it be hosted on https://flathub.org/apps.html?

**Comment by sotch-pr35mac** [comment]
I really want to get it up there, but I'm running into a lot of issues.
Right now the flatpak build keep failing. Hopefully after this weekend I'll
be able to get it working.

I've seen some articles on getting electron apps on flathub, going to see
if they have any suggestions.

On Nov 19, 2017 05:54, "baimafeima" <notifications@github.com> wrote:

That sounds great! Will it be hosted on https://flathub.org/apps.html?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/sotch-pr35mac/syng/issues/77#issuecomment-345507818>,
or mute the thread

**Comment by sotch-pr35mac** [comment]
Unfortunately I can not get the installer to work. There is a platform agnostic installer included in this release, but I don't think I will be able to get flatpak working. 

You are welcome to try it on your machine. I don't see many other people having the same issue as me, so if you think you might be able to get it working it would be much appreciated! Otherwise I'm going to leave this issue closed and try again with the next release, hopefully there will be more support for building flatpak's for electron apps. 

Let me know if you want to try it on your machine, and I can put together what I tried to get it to work.

**Comment by baimafeima** [comment]
Thanks for your efforts in getting the installer to work. Flatpak is just one idea among others, so let's not waste more time on it, for now. Another idea to actually make your software available is to get it included in several major distributions. As soon as it leaves beta here on GitHub, this could be a more viable way.

**Comment by sotch-pr35mac** [comment]
Yes! Major update. I agree. Syng was written in web technologies using a framework called Electron, which is great for cross platform compatibility, and great because it let me develop Syng pretty quickly (as a student, it can be hard to find time to maintain), however, it makes it harder to get Syng to work with platform ecosystem. For example, I am also finding it hard to get Syng into the Mac App Store. 

Because the only place to download Syng is the website and github, it makes me tentative to release too often, because there are no update channels, users have to go to the website/github and update Syng themselves. So I am definitely looking for a better way to distribute Syng. I was even considering, after I accomplish what is currently in the [roadmap](https://github.com/sotch-pr35mac/syng/blob/master/ROADMAP.md) to rewrite Syng as a native app on each platform.

**Comment by baimafeima** [comment]
> however, it makes it harder to get Syng to work with platform ecosystem. For example, I am also finding it hard to get Syng into the Mac App Store, Windows Store, and linux repositories.

@sotch-pr35mac Unfortunately, Syng got rejected for inclusion into the Solus repositories due to it being a Node-based application. See: https://dev.solus-project.com/T957 
Do you still have plans to rewrite Syng as a native application for Linux-based operating systems? 

Alternatively, is there a chance to try again with a flatpak or snap release? I'm not sure which one would be easier: https://snapcraft.io/ and https://flathub.org/home
It looks like Snaps could be auto-build from GitHub via the above-mentioned link.

**Comment by sotch-pr35mac** [comment]
I actually do have plans on rewriting Syng to be a native Linux app, but not for a while. My main focus right now is to finish up the features I am working on for the current desktop app (see the issues page) and then start building out a web and mobile app as well. After I get all that setup I was going to work on building out a native Linux, macOS, and Windows app (in that order). 

However, in the mean time, I am totally open to trying to build a flatpak or snap for distribution on Linux. I'll try building it when I'm ready to cut the next release (v1.4.0).

**Comment by baimafeima** [comment]
> However, in the mean time, I am totally open to trying to build a flatpak or snap for distribution on Linux. I'll try building it when I'm ready to cut the next release (v1.4.0).

Thanks a lot! Flatpak has also recently reached 1.0: https://flatpak.org/press/2018-08-20-flatpak-1.0/

**Comment by sotch-pr35mac** [comment]
Clearing out tasks that are no longer relevant.
