### ISSUE TITLE
Improve pinyinization

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#78]
Do you think it's possible to incorporate this into your project (see examples)? 
https://github.com/hotoo/pinyin
http://pinyin.hotoo.me/examples/

**Comment by sotch-pr35mac** [comment]
In one of the latest commits to the `develop` branch, the pinyin package was updated to [pinyin.js](https://github.com/song940/pinyin.js). A new feature was added as well, 'Pinyinify', to take 汉字 and turn it into 拼音.  If this is the type of feature you're talking about you and you want to use it now you can build the `develop` branch from source. The `develop` branch has most of the current Syng's features and is pretty stable, but it not ready yet to be merged into master.

If the 'Pinyinify' feature isn't what your talking about, and you think that [hotoo's pinyin package](https://github.com/hotoo/pinyin) should be implemented over [pinyin.js](https://github.com/song940/pinyin.js) feel free to let me know and I will consider moving to that one.  Otherwise I'll close this issue.

### The Pinyinify Feature
![pinyinify](https://user-images.githubusercontent.com/441131/30276157-e7a54f5e-96d1-11e7-9ef2-d12bd18254a0.png)

### Guide to Building `develop` from source
This assumes you have [node](https://nodejs.org/en/) and [npm](https://www.npmjs.com/) installed. 
1. Clone the repo `git clone https://github.com/sotch-pr35mac/syng.git'
2. Get into the Project `cd syng`
3. Checkout the `develop` branch `git checkout develop`
4. Install dependencies `npm install`
5. Start Syng `npm start`

**Comment by baimafeima** [comment]
Thanks a lot for the feedback. At a first look hotoo's pinyin package seems to be much more popular and offers more customization options but I am not qualified enough to evaluate this and would leave this up to you. I just raised this issue to ask whether this is something you would look into.

**Comment by sotch-pr35mac** [comment]
Closing this issue since improved pinyinization has been implemented into the `develop` branch.
